mysite/blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'
urlpatterns = [
    path('', views.PostLV.as_view(), name='index'),
    path('post/', views.PostLV.as_view(), name='post_list'),
    path('post/<slug:slug>/', views.PostDV.as_view(), name='post_detail'),

    path('archive/', views.PostAV.as_view(), name='post_archive'),
    path('<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),
    path('<int:year>/<month>/', views.PostMAV.as_view(), name='post_month_archive'),
    path('<int:year>/<month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),
    path('today/', views.PostTAV.as_view(), name='post_today_archive'),
    path('search/', views.SearchFormView.as_view(), name='search'),

    path('add/', views.PostCreateView.as_view(), name='add'),
    path('change/', views.PostChangeLV.as_view(), name='change'),
    path('post/<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),
    path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
]

mysite/conf/urls.py
from django.contrib import admin
from django.urls import path, include
from conf.views import HomeView, UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('', HomeView.as_view(), name='home'),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(),
         name='register_done'),

    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
]

mysite/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.urls import reverse


class Post(models.Model):
    title = models.CharField('TITLE', max_length=50)
    slug = models.SlugField('SLUG', max_length=50, unique=True, allow_unicode=True,
                            help_text='one word for title alias.')
    description = models.CharField('DESCRIPTION', max_length=100, blank=True,
                                   help_text='simple description text.')
    content = models.TextField('CONTENT')
    create_date = models.DateTimeField('Create Date', auto_now_add=True)
    modify_date = models.DateTimeField('Modify Date', auto_now=True)
    owner = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'my_post'
        ordering = ('-modify_date', )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.slug,))

    def get_previous_post(self):
        return self.get_previous_by_modify_date().get_absolute_url()

    def get_next_post(self):
        return self.get_next_by_modify_date().get_absolute_url()

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title, allow_unicode=True)
        super(Post, self).save(*args, **kwargs)

mysite/blog/forms.py
from django import forms


class PostSearchForm(forms.Form):
    search_word = forms.CharField(label='Search Word')

mysite/blog/views.py
from django.db.models import Q
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, FormView, UpdateView, CreateView, DeleteView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, \
    MonthArchiveView, DayArchiveView, TodayArchiveView

from blog.forms import PostSearchForm
from blog.models import Post
from conf.views import LoginRequiredMixin


class PostLV(ListView):
    model = Post
    template_name = 'blog/post_all.html'
    context_object_name = 'posts'
    paginate_by = 2


class PostDV(DetailView):
    model = Post


class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_date'


class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_date'
    make_object_list = True


class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_date'


class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_date'


class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_date'


class SearchFormView(FormView):
    form_class = PostSearchForm
    template_name = 'blog/post_search.html'

    def form_valid(self, form):
        word = '%s' % self.request.POST['search_word']
        post_list = Post.objects.filter(
            Q(title__icontains=word) |
            Q(description__icontains=word) |
            Q(content__icontains=word)
        ).distinct()

        context = {}
        context['form'] = form  # PostSearchForm 객체
        context['search_term'] = word
        context['object_list'] = post_list

        return render(self.request, self.template_name, context)


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'description', 'content']
    success_url = reverse_lazy('blog:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(PostCreateView, self).form_valid(form)


class PostChangeLV(LoginRequiredMixin, ListView):
    template_name = 'blog/post_change_list.html'

    def get_queryset(self):
        return Post.objects.filter(owner=self.request.user)


class PostUpdateView(LoginRequiredMixin, UpdateView) :
    model = Post
    fields = ['title', 'slug', 'description', 'content']
    success_url = reverse_lazy('blog:index')


class PostDeleteView(LoginRequiredMixin, DeleteView) :
    model = Post
    success_url = reverse_lazy('blog:index')

mysite/conf/views.py
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.base import TemplateView


class HomeView(TemplateView):
    template_name = 'home.html'


class UserCreateView(CreateView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('register_done')


class UserCreateDoneTV(TemplateView):
    template_name = 'registration/register_done.html'


class LoginRequiredMixin(object):
    @classmethod
    def as_view(cls, **initkwargs):
        view = super(LoginRequiredMixin, cls).as_view(**initkwargs)
        return login_required(view)

mysite/blog/templates/blog/post_all.html
{% extends "base.html" %}

{% block title %}post_all.html{% endblock %}

{% block content %}
    <div id="content">
        <h1>Blog List</h1>
        {% for post in posts %}
            <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
            {{ post.modify_date|date:"N d, Y" }}
            <p>{{ post.description }}</p>
        {% endfor %}

        <br>

        <div>
            <span>
                <!-- page_obj: 장고의 Page 객체가 들어 있는 context 변수 by ListView-->
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}">Previous Page</a>
                {% endif %}

                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">Next Page</a>
                {% endif %}
            </span>
        </div>
    </div>
{% endblock %}

mysite/blog/templates/blog/post_archive.html
{% extends "base.html" %}

{% block title %}post_archive.html{% endblock %}

{% block content %}
    <div id="content">
        <h1>Post Archives until {% now "N d, Y" %}</h1>
        <ul>
            {% for date in date_list %}
            <li style="display: inline;">
                <a href="{% url 'blog:post_year_archive' date|date:'Y' %}">Year-{{ date|date:"Y" }}</a></li>
            {% endfor %}
        </ul>
        <br/>

        <div>
            <ul>
                {% for post in object_list %}
                <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

mysite/blog/templates/blog/post_archive_day.html
{% extends "base.html" %}

{% block title %}post_archive_day.html{% endblock %}

{% block content %}
    <div id="content">
        <h1>Post Archives for {{ day|date:"N d, Y" }}</h1>

        <div>
            <ul>
                {% for post in object_list %}
                <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

mysite/blog/templates/blog/post_archive_month.html
{% extends "base.html" %}

{% block title %}post_archive_month.html{% endblock %}

{% block content %}
    <div id="content">
        <h1>Post Archives for {{ month|date:"N, Y" }}</h1>

        <div>
            <ul>
                {% for post in object_list %}
                <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

mysite/blog/templates/blog/post_archive_year.html
{% extends "base.html" %}

{% block title %}post_archive_year.html{% endblock %}

{% block content %}
    <div id="content">
        <h1>Post Archives for {{ year|date:"Y" }}</h1>

        <ul>
            {% for date in date_list %}
            <li style="display: inline;">
                <a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'b' %}">{{ date|date:"F" }}</a></li>
            {% endfor %}
        </ul>
        <br/>

        <div>
            <ul>
                {% for post in object_list %}
                <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

mysite/blog/templates/blog/post_change_list.html
{% extends "base.html" %}

{% block title %}post_change_list.html{% endblock %}

{% block content %}
<div id="content">

    <h1>Post Change - {{user}}</h1>
    
    <table class="change-list">
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
    
        {% for item in object_list %}
        <tr>
            <td>{{ item.title }}</td>
            <td>{{ item.description }}</td>
            <td>{{ item.owner }}</td>
            <td><a href="{% url 'blog:update' item.id %}">Update</a></td>
            <td><a href="{% url 'blog:delete' item.id %}">Delete</a></td>
        </tr>
        {% endfor %}
    </table>

</div>
{% endblock %}

mysite/blog/templates/blog/post_confirm_delete.html
{% extends "base.html" %}

{% block title %}post_confirm_delete.html{% endblock %}

{% block content %}
<div id="content">

    <h1>Post Delete</h1>

    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm" />
    </form>

</div>
{% endblock %}

mysite/blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% block title %}post_detail.html{% endblock %}

{% block content %}
    <div id="content">
        <h2>{{ object.title }}</h2>

        <p class="other_posts">
            {% if object.get_previous_by_modify_date %}
                <a href="{{ object.get_previous_post }}"
                   title="View Previous Post">&laquo;--{{ object.get_previous_by_modify_date }}</a>
            {% endif %}

            {% if object.get_next_by_modify_date %}
                <a href="{{ object.get_next_post }}"
                   title="View Next Post">{{ object.get_next_by_modify_date }}--&raquo;</a>
            {% endif %}
        </p>

        <p class="date">{{ object.modify_date|date:"j F Y" }}</p>
        <br>

        <div class="body">
            {{ object.content|linebreaks }}
        </div>
    </div>
{% endblock %}

mysite/blog/templates/blog/post_form.html
{% extends "base.html" %}

{% block title %}post_form.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<div id="content">

    <h1>Post Create/Update - {{user}}</h1>

    <form action="." method="post">{% csrf_token %}

    {% if form.errors %}
    <p class="errornote">Wrong! Please correct the error(s) below.</p>
    {% endif %}

    <p>This is a creation or update form for your post.</p>

    <fieldset class="aligned">

        <div class="form-row">
            {{ form.title.label_tag }} {{ form.title }}
        </div>
    
        <div class="form-row">
            {{ form.slug.label_tag }} {{ form.slug }}
        </div>

        <div class="form-row">
            {{ form.description.label_tag }} {{ form.description }}
        </div>

        <div class="form-row">
            {{ form.content.label_tag }} {{ form.content }}
        </div>

        <div class="form-row">
            {{ form.tag.label_tag }} {{ form.tag }}
        </div>

    </fieldset>

    <div class="submit-row">
        <input type="submit" value="Submit"/>
    </div>

    <script type="text/javascript">document.getElementById('id_title').focus();</script>
    </form>

</div>
{% endblock %}

mysite/blog/templates/blog/post_search.html
{% extends "base.html" %}

{% block title %}post_search.html{% endblock %}

{% block content %}
    <div id="content">

    <h1>Blog Search</h1>

    <form action="." method="post"> {% csrf_token %}
        {{ form.as_table }}     <!-- form은 뷰에서 넘겨준 PostSearchForm 객체-->
        <input type="submit" value="Submit" />
    </form>

    <br/><br/>

    {% if object_list %}
    {% for post in object_list %}
        <h2><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h2>
        {{ post.modify_date|date:"N d, Y" }}
        <p>{{ post.description }}</p>
    {% endfor %}

    {% elif search_term %}
    <b><i>Search Word({{ search_term }}) Not Found !</i></b>
    {% endif %}

    </div>
{% endblock %}

mysite/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
<title>{% block title %}Django Web Programming{% endblock %}</title>

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "css/base.css" %}{% endblock %}" />
<link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}" />

</head>

<body>

<div id="header">
    <h2 class="maintitle">Easy&amp;Fast Django Web Programming</h2>
    {% if user.is_active %}
        <h4 class="welcome">Welcome,
            <strong>{% firstof user.get_short_name user.get_username %}</strong> /
            <a href="{% url 'password_change' %}">Change Password</a> /
            <a href="{% url 'logout' %}">Logout</a>
        </h4>
    {% else %}
        <h4 class="welcome">Welcome, Anonymous /
            <a href="{% url 'login' %}">Login</a> /
            <a href="{% url 'register' %}">Register</a>
        </h4>
    {% endif %}
</div>

<div id="menu">
    <li><a href="{% url 'home' %}">Home</a></li>
    <li><a href="{% url 'blog:index' %}">Blog</a></li>

    <li><a href="#">Add&bigtriangledown;</a>
        <ul>
            <li><a href="{% url 'blog:add' %}">Blog</a></li>
        </ul>
    </li>
    <li><a href="#">Change&bigtriangledown;</a>
        <ul>
            <li><a href="{% url 'blog:change' %}">Blog</a></li>
        </ul>
    </li>

    <li><a href="{% url 'blog:post_archive' %}">Archive</a></li>
    <li><a href="{% url 'blog:search' %}">Search</a></li>
    <li><a href="{% url 'admin:index' %}">Admin</a></li>
</div>

{% block content %}{% endblock %}

{% block footer %}{% endblock %}

</body>
</html>

mysite/templates/home.html
{% extends "base.html" %}

{% block title %}home.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/home.css" %}{% endblock %}

{% block content %}

<div id="content_home">

    <div id="homeimg">
        <a href="/"><img src="{% static 'img/django-actor-big.jpg' %}" style="height:256px;"/></a>
        <h4 style="margin: 0;">This is Django powered web site.</h4>
    </div>

    <hr style="margin: 5px 0;">

    <h2>Select Application</h2>

    <table id="applist">

        <tr>
        <td><b><i><a href="{% url 'blog:index' %}">Blog</a></i></b></td>
        <td>You can write your own post and share to others. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo</td>
        <td id="Edit"><i><a href="{% url 'blog:add' %}">Add</a></i></td>
        <td id="Edit"><i><a href="{% url 'blog:change' %}">Change</a></i></td>
        </tr>
    </table>
</div>
{% endblock content %}

{% block footer %}
<div id="footer">
    &copy; cupjoo 2016
</div>
{% endblock footer %}